POST https://{{$dotenv SAP_TENANT}}.callidusondemand.com/api/v2/spamm HTTP/1.1
Authorization: Basic {{$dotenv SAP_USERNAME}}:{{$dotenv SAP_PASSWORD}}
content-type: application/json

[
    {
        "name": "eggs",
        "description": "bacon",
        "effectiveStartDate": "2025-01-01",
        "effectiveEndDate": "2200-01-01"
    }
]
